//! `cargo xtask generate-cases` run as the binary over a scratch tree: the
//! committed file it writes from `tests/cases/<feature>/*.toml`, and the gate
//! that fails, before anything compiles, when a case was added without it.

use std::path::{Path, PathBuf};
use std::process::Output;

mod support;

const GENERATED: &str = "tests/scenarios/cases_generated.rs";

/// A scratch repository with two features' cases, a matrix declaration
/// directly under `tests/cases/` and an unrelated file in a feature directory.
fn scratch(name: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!("xtask-cases-{name}-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    for (path, body) in [
        ("tests/cases/oauth/oauth_b_second.toml", "id = \"b\"\n"),
        ("tests/cases/api-client/api_a_first.toml", "id = \"a\"\n"),
        ("tests/cases/oauth/notes.md", "not a case\n"),
        ("tests/cases/not-applicable.toml", "[[not_applicable]]\n"),
    ] {
        write(&dir, path, body);
    }
    std::fs::create_dir_all(dir.join("tests/scenarios")).unwrap();
    // `branch-check` takes its slot in the clone's git directory first.
    let init = std::process::Command::new("git")
        .args(["init", "-q"])
        .current_dir(&dir)
        .status()
        .unwrap();
    assert!(init.success());
    dir
}

fn write(dir: &Path, path: &str, body: &str) {
    let path = dir.join(path);
    std::fs::create_dir_all(path.parent().unwrap()).unwrap();
    std::fs::write(path, body).unwrap();
}

fn run(dir: &Path, args: &[&str]) -> Output {
    support::xtask(dir)
        .args(args)
        .env("KURAMA_XTASK_ROOT", dir)
        .output()
        .unwrap()
}

#[test]
fn cases_generated_file_matches_the_cases() {
    let dir = scratch("matches");

    let output = run(&dir, &["generate-cases"]);

    assert!(output.status.success(), "{output:?}");
    let generated = std::fs::read_to_string(dir.join(GENERATED)).unwrap();
    let gate =
        "#[cfg_attr(not(feature = \"test-fakes\"), ignore = \"needs --features test-fakes\")]";
    assert_eq!(
        generated,
        format!(
            "// Generated by `cargo xtask generate-cases`: one test per case file under\n\
             // tests/cases/<feature>/. Do not edit; rerun it when a case is added,\n\
             // removed or renamed.\n\
             #[test]\n{gate}\nfn api_a_first() {{\n    \
             crate::support::cases::run_case(\n        \
             include_str!(\"../cases/api-client/api_a_first.toml\"),\n        \
             \"tests/cases/api-client/api_a_first.toml\",\n    );\n}}\n\
             #[test]\n{gate}\nfn oauth_b_second() {{\n    \
             crate::support::cases::run_case(\n        \
             include_str!(\"../cases/oauth/oauth_b_second.toml\"),\n        \
             \"tests/cases/oauth/oauth_b_second.toml\",\n    );\n}}\n"
        )
    );
    // Nothing of the checkout is in it, and a second run changes nothing.
    assert!(!generated.contains(&*dir.to_string_lossy()));
    assert!(run(&dir, &["generate-cases"]).status.success());
    assert_eq!(
        std::fs::read_to_string(dir.join(GENERATED)).unwrap(),
        generated
    );
    std::fs::remove_dir_all(&dir).unwrap();
}

#[test]
fn cases_stale_generated_file_fails_the_gate() {
    let dir = scratch("stale");
    let added = "tests/cases/oauth/oauth_c_added.toml";
    let changes: [(&str, &dyn Fn()); 2] = [
        ("added", &|| write(&dir, added, "id = \"c\"\n")),
        ("deleted", &|| {
            std::fs::remove_file(dir.join(added)).unwrap()
        }),
    ];
    for (change, apply) in changes {
        assert!(run(&dir, &["generate-cases"]).status.success());
        apply();

        for command in ["branch-check", "check", "doctor"] {
            let output = run(&dir, &[command]);

            assert!(!output.status.success(), "{change} {command}: {output:?}");
            let stderr = String::from_utf8_lossy(&output.stderr);
            assert!(
                stderr.contains(GENERATED) && stderr.contains("run `cargo xtask generate-cases`"),
                "{change} {command}: {stderr}"
            );
            // It is the first thing the command did: no cargo ran before it.
            assert!(
                !stderr.contains("==> format"),
                "{change} {command}: {stderr}"
            );
            assert!(
                !String::from_utf8_lossy(&output.stdout).contains("rust toolchain"),
                "{change} {command}"
            );
        }
    }
    std::fs::remove_dir_all(&dir).unwrap();
}
