//! `cargo xtask generate-cases`: one `#[test]` per case file, written to the
//! committed file `tests/scenarios/main.rs` includes, and the freshness check
//! the static checks and `doctor` run before anything compiles.
//!
//! The file is committed rather than generated by `build.rs` so that editing a
//! case does not rerun the build script and rebuild the whole package: each
//! test reads its case through `include_str!`, which rebuilds only the
//! scenario binary when the case's content changes. Only adding, removing or
//! renaming a case changes the file, and the check names the command then.

use std::path::Path;

use crate::root;

/// The generated file, relative to the repository.
pub const GENERATED: &str = "tests/scenarios/cases_generated.rs";

/// Write the generated file from the cases in the tree.
pub fn generate_cases() -> Result<(), String> {
    let (source, count) = generated()?;
    let path = root().join(GENERATED);
    std::fs::write(&path, source).map_err(|error| format!("{}: {error}", path.display()))?;
    eprintln!("wrote {GENERATED}: {count} cases");
    Ok(())
}

/// Fail when the committed file is not what `generate_cases` would write.
pub fn check_generated() -> Result<(), String> {
    let (expected, _) = generated()?;
    let committed = std::fs::read_to_string(root().join(GENERATED)).unwrap_or_default();
    if committed == expected {
        return Ok(());
    }
    Err(format!(
        "{GENERATED} does not match the cases under tests/cases/: a case was added, removed or renamed; run `cargo xtask generate-cases` and commit the file"
    ))
}

/// The generated source and the number of cases in it. A `.toml` directly
/// under `tests/cases/` is a declaration the matrix reads (not-applicable,
/// needs-human), not a case: only the feature directories hold cases, one
/// level deep, as the feature map and the matrix read them. Every case is
/// ignored without `test-fakes`: it runs the binary against the fake session
/// cache, token store and endpoints that feature compiles in, and `verify`
/// always builds with it.
/// Why `id` cannot name the test a case becomes: a Rust function name, so
/// snake case and nothing else.
fn case_name_problem(feature: &str, id: &str) -> Option<String> {
    let snake = |c: char| c.is_ascii_lowercase() || c.is_ascii_digit() || c == '_';
    (id.is_empty() || !id.chars().all(snake)).then(|| {
        format!(
            "tests/cases/{feature}/{id}.toml: a case file is named <feature>_<behavior>.toml in snake case"
        )
    })
}

fn generated() -> Result<(String, usize), String> {
    let files = case_files(&root())?;
    let mut out = String::from(
        "// Generated by `cargo xtask generate-cases`: one test per case file under\n\
         // tests/cases/<feature>/. Do not edit; rerun it when a case is added,\n\
         // removed or renamed.\n",
    );
    for (feature, id) in files.iter().filter_map(|file| case_path(file)) {
        if let Some(problem) = case_name_problem(feature, id) {
            return Err(problem);
        }
        out.push_str(&format!(
            "#[test]\n\
             #[cfg_attr(not(feature = \"test-fakes\"), ignore = \"needs --features test-fakes\")]\n\
             fn {id}() {{\n    \
             crate::support::cases::run_case(\n        \
             include_str!(\"../cases/{feature}/{id}.toml\"),\n        \
             \"tests/cases/{feature}/{id}.toml\",\n    \
             );\n\
             }}\n"
        ));
    }
    Ok((out, files.len()))
}

/// Every case file, `tests/cases/<feature>/<id>.toml` relative to `root`, in
/// path order. Only the feature directories hold cases, one level deep.
pub(crate) fn case_files(root: &Path) -> Result<Vec<String>, String> {
    let mut files = Vec::new();
    let features = std::fs::read_dir(root.join("tests/cases"))
        .into_iter()
        .flatten()
        .flatten()
        .map(|entry| entry.path())
        .filter(|path| path.is_dir());
    for dir in features {
        for entry in std::fs::read_dir(&dir)
            .map_err(|e| format!("{}: {e}", dir.display()))?
            .flatten()
        {
            let path = entry.path();
            if path.extension().is_some_and(|ext| ext == "toml")
                && let Ok(relative) = path.strip_prefix(root)
            {
                files.push(relative.display().to_string());
            }
        }
    }
    files.sort_by(|a, b| Path::new(a).cmp(Path::new(b)));
    Ok(files)
}

/// The feature and the file name of a case file, from its path relative to
/// the repository. A case is `tests/cases/<feature>/<id>.toml`; a `.toml`
/// directly under `tests/cases/` is a declaration the matrix reads, not a
/// case.
pub(crate) fn case_path(file: &str) -> Option<(&str, &str)> {
    let (feature, rest) = file.strip_prefix("tests/cases/")?.split_once('/')?;
    let id = rest.strip_suffix(".toml")?;
    (!id.contains('/')).then_some((feature, id))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_case_is_named_in_snake_case_or_refused() {
        assert_eq!(case_name_problem("db", "db_reads_a_table_2"), None);
        for id in ["", "DbReads", "db-reads", "db reads", "ö"] {
            let problem = case_name_problem("db", id).expect(id);
            assert!(
                problem.starts_with(&format!("tests/cases/db/{id}.toml: ")),
                "{problem}"
            );
        }
    }

    /// A case file is claimed by the feature its directory is named after;
    /// a file elsewhere under tests/cases/, or not a case, is claimed by
    /// nobody this way.
    #[test]
    fn a_case_file_belongs_to_the_feature_of_its_directory() {
        let feature = |file| case_path(file).map(|(feature, _)| feature);
        assert_eq!(
            feature("tests/cases/api-client/api_x.toml"),
            Some("api-client")
        );
        assert_eq!(feature("tests/cases/api-client/notes.md"), None);
        assert_eq!(feature("tests/cases/README.md"), None);
        assert_eq!(feature("tests/scenarios/api_client.rs"), None);
    }

    #[test]
    fn a_case_file_names_the_scenario_it_declares() {
        let case_name = |file| case_path(file).map(|(_, id)| id);
        assert_eq!(
            case_name("tests/cases/config/config_x_exits_2.toml"),
            Some("config_x_exits_2")
        );
        assert_eq!(case_name("tests/cases/config/README.md"), None);
        assert_eq!(case_name("tests/cases/not-applicable.toml"), None);
        assert_eq!(case_name("tests/cases/unclassified-baseline.toml"), None);
        assert_eq!(case_name("tests/scenarios/config.rs"), None);
    }
}
